### ISSUE TITLE
Scaffolded Item

### ISSUE THREAD

**Issue by mohammedhammaad18** [DMU-CTEC2902-2022/BrainStormers_Team#13]
The developer is having issues adding scaffolded item which is a MVC controller for the module class. An error keeps on popping up.

**Comment by IbrahimZahid1** [comment]
I as the developer booked a meeting with the tutor and resolved the issue, the issue was coming as I was trying to add a scaffolded item, the solution was to add the library "using System.ComponentModel.DataAnnotations;" and use "[Key]" in the model class before the primary key or just use the public virtual int Id {Get; Set;} instead.
